version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - hr-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://hr-db:3306/hr?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    container_name: hr-employee-app
    networks:
      - hr-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3

  hr-db:
    image: mbn217/hr-employee-db:final
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - hr-network
    container_name: hr-db

networks:
  hr-network:
    driver: bridge